### ISSUE TITLE
Great! CSS

### ISSUE THREAD

**Issue by kalverra** [22scofield/prj-rev-bwfs-dasmoto#5]
https://github.com/22scofield/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L1

Nice, organized, and condensed CSS. Check out this style guide to help even more. https://google.github.io/styleguide/htmlcssguide.html

**Comment by 22scofield** [comment]
Thanks! I'm glad, that was good :)
